sudo: required
services:
  - docker

before_install:
  - docker build -t felixoberhardt/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true felixoberhardt/react-test npm test

after_success:
  - docker build -t felixoberhardt/multi-client ./client
  - docker build -t felixoberhardt/multi-nginx ./nginx
  - docker build -t felixoberhardt/multi-server ./server
  - docker build -t felixoberhardt/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push felixoberhardt/multi-client
  - docker push felixoberhardt/multi-nginx
  - docker push felixoberhardt/multi-server
  - docker push felixoberhardt/multi-worker
